### ISSUE TITLE
Username validation doesn't work properly

### ISSUE THREAD

**Issue by Plazmaz** [Northcodeno/northcode.no#11]
After registering with the username, "../../", I can log in to cobaltvault.no as ../../. This throws an error briefly on the login page before redirect. It appears the regex code validating usernames is broken, though I had difficulty determining why. Perhaps an inconsistency between what's on the server and what's on Github?

**Comment by Jenjen1324** [comment]
``` php
if (isset($_POST['username'])) {
    //code...
    $username = $_POST['username'];
}

if (isset($_POST['email'])) {
    //code...
    $email = $_POST['email'];
}

if (isset($_POST['password'])) {
    //code...
    $password = $_POST['password'];
}
```

My cousin had a lazy day I guess...

**Comment by Northcode** [comment]
My bad, sorry

**Comment by Jenjen1324** [comment]
Enhancement to this: #12
